project:
  type: website

website:
  title: "ISSS626"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1 A"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_a.html" 
          - text: "Hands-on Exercise 1 B"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_b.html" 
          - text: "Hands-on Exercise 2 A"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_a.html"  
          - text: "Hands-on Exercise 2 B"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_b.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1 "
            href: "Inclass_Ex/Inclass_Ex01/Inclass_Ex01.html" 
          - text: "In-class Exercise 2 "
            href: "Inclass_Ex/Inclass_Ex02/Inclass_Ex02.html"
          - text: "In-class Exercise 3 "
            href: "Inclass_Ex/Inclass_Ex03/Inclass_Ex03.html"
          - text: "In-class Exercise 4 "
            href: "Inclass_Ex/Inclass_Ex04/Inclass_Ex04.html" 
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1 "
            href: "Takehome_Ex/Takehome_Ex01/Takehome_Ex01.html" 
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

