project:
  type: website

website:
  title: "ISSS626"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Exercise 1 A"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html" 
          - text: "Hands-on Exercise 1 B"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_b.html" 
          - text: "Hands-on Exercise 2 A"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_a.html"  
          - text: "Hands-on Exercise 2 B"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02_b.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands-on Exercise 5 A"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_a.html"
          - text: "Hands-on Exercise 5 B"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05_b.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          - text: "Hands-on Exercise 8 A"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_a.html"
          - text: "Hands-on Exercise 8 B"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_b.html"
          - text: "Hands-on Exercise 8 C"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_c.html"
          - text: "Hands-on Exercise 9 A"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex09_a.html"
          - text: "Hands-on Exercise 9 B"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_b.html"
          - text: "Hands-on Exercise 9 C"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_c.html"
          - text: "Hands-on Exercise 9 D"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09_d.html"
          - text: "Hands-on Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
      - text: "In-class Exercise"
        menu: 
          - text: "In-class Exercise 1 "
            href: "Inclass_Ex/Inclass_Ex01/Inclass_Ex01.html" 
          - text: "In-class Exercise 2 "
            href: "Inclass_Ex/Inclass_Ex02/Inclass_Ex02.html"
          - text: "In-class Exercise 3 "
            href: "Inclass_Ex/Inclass_Ex03/Inclass_Ex03.html"
          - text: "In-class Exercise 4 "
            href: "Inclass_Ex/Inclass_Ex04/Inclass_04.html"
          - text: "In-class Exercise 5 "
            href: "Inclass_Ex/Inclass_Ex05/Inclass_Ex05.html" 
          - text: "In-class Exercise 6 "
            href: "Inclass_Ex/Inclass_Ex06/Inclass_Ex06.html" 
          - text: "In-class Exercise 7 "
            href: "Inclass_Ex/Inclass_Ex07/Inclass_Ex07.html" 
          - text: "In-class Exercise 8 "
            href: "Inclass_Ex/Inclass_Ex08/Inclass_Ex08.html" 
          - text: "In-class Exercise 9 "
            href: "Inclass_Ex/Inclass_Ex09/Inclass_Ex09.html" 
          - text: "In-class Exercise 10 "
            href: "Inclass_Ex/Inclass_Ex10/Inclass_Ex10.html" 
      - text: "Take-home Exercise"
        menu: 
          - text: "Take-home Exercise 1 "
            href: "Takehome_Ex/Takehome_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2 "
            href: "Takehome_Ex/Takehome_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3 "
            href: "Takehome_Ex/Takehome_Ex03/Take-home_Ex03.html"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

