---
title: "Inclass_Ex06"
author: "Fu Wanqian"
---

```{r}
pacman::p_load(sf,sfdep,tmap,plotly,tidyverse,Kendall)
```

```{r}
hunan<- st_read(dsn="data/geospatial", layer="Hunan")
```

```{r}
GDPPC<- read_csv("data/aspatial/Hunan_GDPPC.csv")
```

# Create a tiem series cube

```{r}
GDPPC_st<- spacetime(GDPPC, hunan,
                       .loc_col = "County",
                       .time_col = "Year")

is_spacetime_cube(GDPPC_st)
```

# Computing Gi\*

# Deriving the spatial weights

```{r,eval=FALSE}
GDPPC_nb <- GDPPC_st %>%
  activate("geometry") %>%
  mutate(nb = include_self(
    st_contiguity(geometry)),
    wt = st_inverse_distance(nb,
                             geometry,
                             scale = 1,
                             alpha = 1),
    .before = 1) %>%
  set_nbs("nb") %>%
  set_wts("wt")
```

```{r, eval=FALSE}
gi_stars <- GDPPC_nb %>%
  group_by(Year) %>%
  mutate(gi_star = local_gstar_perm(
    GDPPC, nb, wt)) %>%
  tidyr::unnest(gi_star)
```

```{r,eval=FALSE}
cbg <- gi_stars %>%
  ungroup()%>%
  filter(County=="Changsha") |>
  select(County, Year, gi_star)
```

```{r,eval=FALSE}
ggplot(data=cbg,
       aes(x=Year,
           y=gi_star))+
  geom_line()+
  theme_light
```

```{r,eval=FALSE}
cbg %>%
  summarise(mk = list(
    unclass(
      Kendall::MannKendall(gi_star)))) %>%
  tidyr::unnest_wider(mk)
```

```{r,eval=FALSE}
ehsa <- gi_stars %>%
  group_by(County) %>%
  summarise(mk = list(
    unclass(
      Kendall::MannKendall(gi_star)))) %>%
  tidyr::unnest_wider(mk)
ehsa
```
