---
title: "Inclass_Ex03"
author: "Fu Wanqian"
execute: 
  echo: true
  cache: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(sf, spNetwork, tmap, tidyverse)
```

```{r}
network <- st_read(dsn="data/geospatial", 
                   layer="Punggol_St")
```

```{r}
childcare <- st_read(dsn="data/geospatial",
                     layer="Punggol_CC")
```

```{r}
childcare2 = st_zm(childcare, drop = TRUE,
        what = "ZM")
```

```{r}
childcare
```

```{r}
network
```

```{r}
plot(st_geometry(network))
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
plot(network)
plot(childcare,add=T,col='red',pch = 19)
```

```{r}
tmap_mode('view')
tm_shape(childcare) + 
  tm_dots(col="red") + 
  tm_shape(network) +
  tm_lines()
tmap_mode('plot')
```

```{r}
lixels <- lixelize_lines(network, 
                         700, 
                         mindist = 350)
```

```{r}
samples <- lines_center(lixels) 
```

```{r}
tmap_mode('view')
tm_shape(lixels) +
  tm_lines(col = 'blue') +
  tm_shape(samples) +
  tm_dots() 
tmap_mode('plot')
```

```{r}
densities <- nkde(network, 
                  events = childcare2,
                  w = rep(1, nrow(childcare2)),
                  samples = samples,
                  kernel_name = "quartic",
                  bw = 300, 
                  div= "bw", 
                  method = "simple", 
                  digits = 1, 
                  tol = 1,
                  grid_shape = c(1,1), 
                  max_depth = 8,
                  agg = 5, 
                  sparse = TRUE,
                  verbose = FALSE)
```

```{r}
densities1 <- nkde(network, 
                  events = childcare,
                  w = rep(1, nrow(childcare)),
                  samples = samples,
                  kernel_name = "quartic",
                  bw = 300, 
                  div= "bw", 
                  method = "simple")
```

```{r}
samples$density <- densities
lixels$density <- densities
```

```{r}
# rescaling to help the mapping
samples$density <- samples$density*1000
lixels$density <- lixels$density*1000
```

```{r}
tmap_mode('view')
tm_shape(lixels)+
  tm_lines(col="density")+
tm_shape(childcare)+
  tm_dots()
tmap_mode('plot')
```

```{r}
kfun_childcare <- kfunctions(network, 
                             childcare,
                             start = 0, 
                             end = 1000, 
                             step = 50, 
                             width = 50, 
                             nsim = 50, 
                             resolution = 50,
                             verbose = FALSE, 
                             conf_int = 0.05)
kfun_childcare$plotk
```
