---
title: "Inclass_Ex05"
author: "FU Wanqian"
execute: 
  echo: true
  eval: False
  warning: false
  freeze: true
  cache: true
---

```{r, cache=TRUE}
pacman::p_load(sf, tidyverse, tmap, sfdep)                                
```



```{r}
Hunan_2012 <- read.csv('data/aspatial/Hunan_2012.csv') 

hunan <- st_read(dsn = "data/geospatial", 
                         layer = "hunan")                          
```

```{r}
hunan_GDPPC <- left_join(hunan, hunan2012) %>%
  select(1:4, 7, 15)                             
```

```{r}
wm_q <- hunan_GDPPC %/%
  mutate(nb = st_contiguity(geometry),
         wt = st_weights(nb,
                        style = "w"),
         .before = 1)                             
```

```{r}
moranI <- global_moran(wm_q$GDPPC,
                       wm_q$nb,
                       wm_q$wt) 

set.seed(1234)
```

```{r}
global_moran_perm(wm_q$GDPCC,
                       wm_q$nb,
                        wm_q$wt,
                  nsim=99)
```



```{r}
lisa <- wm_q %>%
  mutate(local_moran = local_moran(
    GDPPC, nb, wt, nsim = 99),
    .before = 1)%>%
  unnest(local_moran)
```

#visualizing lisa map
```{r,eval=FALSE}

lisa_sig <- lisa%>%
  filter(p_ii<)
```

```{r}
```

```{r}
wm_idw <- hunan_GDPPC




