---
title: "In-class_Ex04"
author: "Fu wanqian"
date: "Sep 16 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

------------------------------------------------------------------------

```{r}
pacman::p_load(sf, ggstatsplot, tmap, tidyverse , GWmodel)
```

## Data Import and Preparation

```{r}
hunan_sf <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
hunan <- left_join(hunan_sf,hunan2012)%>%
  select(1:3, 7, 15, 16, 31, 32)
```

#left join

```{r}
hunan_sp = hunan%>%
  as_Spatial()
```

#Determine adaptive bandwidth

```{r}
bw_AIC=bw.gwr(GDPPC~1,data= hunan_sp, approach = "AIC", adaptive = TRUE,
             kernel="bisquare", longlat = T)
bw_AIC
```

#Computationing geograohically wrighted summary statistics

```{r}
gwstat=gwss(
  data = hunan_sp, 
  vars = "GDPPC",
  bw = bw_AIC,
  kernel="bisquare",
  adaptive = TRUE, 
  longlat=T)
```

#preparing the output data

```{r}
gwstat_df = as.data.frame(gwstat$SDF)
hunan_gstat = cbind(hunan_sf,gwstat_df)
```

#Visualizing geographically weighted summary statistics

```{r}
tm_shape(hunan_gstat)+tm_fill("GDPPC_LM",
                              n=5,
                              style = "quantile") +
  tm_borders(alpha=0.5)+
  tm_layout(main.title = "Distributiuon of geographically weighted mean",
            main.title.position = "center",
            main.title.size = 0.8,
            legend.text.size = 1.2,
            legend.height = 1.5,
            legend.width = 1.5,
            frame = TRUE)
```
